fragment DashboardPet on Pet {
	...MinPet
	health_card {
		id
		treatments(
			commonSearch: {
				order_by: "date"
				order_direction: "asc"
				filters: {
					ranges: [
						{
							key: "date"
							value: { min: $date_from, max: $date_to }
						}
					],
					lists: [
						{
							key: "type",
							value: [ "REMINDER", "TABLET", "OPERATION", "TRAINING", "ANTIPARASITIC"]
						}
					]
				}
			}
		) {
			items {
				id
				date
				name
				type
			}
			success
			error {
				code
				message
			}
		}
	}
}
