fragment FullReport on Report {
    id
    medias {
        id
        url
    }
    reporter {
        email
        first_name
        last_name
        user_id
    }
    responders {
        email
    }
    notes
    coordinates {
        latitude
        longitude
    }
    place
    pet {
        id
        name
        years
        weight_kg
        gender
        body {
            breed
        }
        main_picture {
            id
        }
    }
    type
    date
    medias {
        id
    }
}
