name: DEPLOY-DEV
on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build And Deploy on development
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          port: 22
          script: |
            cd projects/graph-a-pet-app
            git pull
            docker image prune -a -f
            docker volume prune -f
            docker system prune -a -f
            docker-compose down --remove-orphans
            docker-compose up -d --build --remove-orphans
            echo 'Deployment finished succesfully'